WangBRen/HMS-Web-Frontend

- src/api/login.js
- src/permission.js
- src/store/modules/permission.js
- src/store/modules/user.js
- src/store/mutation-types.js
- src/utils/request.js
- src/utils/util.js
- src/views/dashboard/Workplace.vue
- src/views/user/Login.vue
> support permission

- src/api/manage.js
- src/config/router.config.js
- src/locales/lang/en-US/menu.js
- src/locales/lang/zh-CN/menu.js
- src/mock/services/other.js
- src/utils/request.js
- src/views/system/AccountList.vue
账户创建，会下载 Excel 文件，文件包含新建的账户信息；用户在一天以内登录则可激活，否则删除该账号
> download excel

- src/views/user/Login.vue
> fix: 密码校验规则

- src/views/user/ForgetPassword.vue
> fix: 修改了密码的校验规则

- src/api/permission.js
- src/config/router.config.js
- src/mock/services/other.js
- src/views/system/PermissionList.vue
> Feature/权限管理   菜单目录

- src/views/system/PermissionList.vue
fix role page render and message
> fix: console.log

- src/views/customer/CustomerManager.vue
- src/views/customer/components/AddNewUser.vue
> feat: 加入分页功能

- src/views/customer/CustomerManager.vue
- src/views/customer/components/AddNewUser.vue
> fix: 修改了行高和头像的大小

- src/views/customer/CustomerManager.vue
- src/views/customer/components/FiltersHealthDataTableHeaders.vue
- src/views/customer/components/HealthDataManagmentForm.vue
> feat: 加入了查看健康数据的弹窗

- src/api/health_indexes.js
- src/config/defaultSettings.js
- src/config/router.config.js
- src/locales/lang/en-US/menu.js
- src/locales/lang/zh-CN/menu.js
- src/permission.js
- src/views/health/IndexPage.vue
clean project, remove useless router
> feat: health index page

- src/views/customer/components/FiltersHealthDataTableHeaders.vue
- src/views/customer/components/HealthDataManagmentForm.vue
> fix: 修复了筛选不同步的bug

- src/api/health.js
- src/views/customer/components/AddHealthData.vue
- src/views/customer/components/CustomerInfoForm.vue
- src/views/customer/components/HealthDataManagmentForm.vue
> fix: 健康检测报告

- src/api/customer.js
- src/components/CheckAddress/CheckAddress.vue
- src/views/customer/CustomerManager.vue
- src/views/customer/components/EditUserMsg.vue
> feat: 用户基础信息编辑

- src/api/health_indexes.js
- src/views/health/IndexPage.vue
> support index edit

- src/views/user/Login.vue
> fix: 首次登陆修改信息

- src/api/customer.js
- src/views/customer/CustomerManager.vue
- src/views/customer/components/EditUserMsg.vue
- src/views/customer/components/HealthDataManagmentForm.vue
> feat: 加入修改手机号的功能

- src/views/customer/components/EditUserMsg.vue
- src/views/user/ForgetPassword.vue
> feat: 加入确认按钮

- src/views/customer/components/EditUserMsg.vue
> fix: 添加验证规则

- src/views/customer/components/AddHealthData.vue
- src/views/customer/components/AddHealthInput.vue
- src/views/customer/components/HealthDataManagmentForm.vue
> fix: 优化新建报告单

- src/views/customer/components/EditUserMsg.vue
- src/views/customer/components/HealthDataManagmentForm.vue
- src/views/user/ForgetPassword.vue
> fix: 修改了columns

- src/api/chronic.js
- src/config/router.config.js
- src/locales/lang/en-US/menu.js
- src/locales/lang/zh-CN/menu.js
- src/main.js
- src/views/health/HealthChronic.vue
- src/views/health/components/HealthChronicName.vue
> feat: 慢病管理/新建慢病

- src/api/chronic.js
- src/views/health/HealthChronic.vue
- src/views/health/HealthChronicEdit.vue
> feat: 添加慢病编辑功能

- src/views/customer/components/HealthDataManagmentForm.vue
- src/views/customer/components/HealthReportAdd.vue
- src/views/customer/components/HealthReportSee.vue
> fix: 优化查看健康信息功能用户交互

- src/api/followUpForm.js
- src/api/health.js
- src/views/customer/components/AddFollowUpSheet.vue
- src/views/customer/components/ChronicInformation.vue
- src/views/customer/components/ChronicInformationVisit.vue
- src/views/customer/components/FollowUpRecords.vue
- src/views/health/HealthChronic.vue
feat: 随访单编辑页以及预览发送信息
https://www.leangoo.com/kanban/board/go/4546002/5551677e09ede0e1
https://www.leangoo.com/kanban/board/go/4546002/463911a64c5e3f6d
> feat: 随访单编辑页以及预览发送信息

- src/api/followUpForm.js
- src/views/customer/components/AddFollowUpSheet.vue
- src/views/customer/components/ChronicInformation.vue
- src/views/customer/components/FollowUpRecords.vue
- src/views/customer/components/SeeFollowUpSheet.vue
> Feat /folloe up form record

- src/views/customer/components/ChronicInformationEcharts.vue
> fix: 优化echarts图

- src/api/followUpForm.js
- src/views/customer/components/AddFollowUpSheet.vue
- src/views/customer/components/ChronicInformation.vue
- src/views/customer/components/ChronicInformationVisit.vue
- src/views/customer/components/FollowUpRecords.vue
- src/views/customer/components/GradeModel.vue
- src/views/customer/components/SeeFollowUpSheet.vue
> Feat  one add follow up sheet

- src/views/customer/components/ChronicInformation.vue
> fix: 优化卡片展开收起功能

- .github/workflows/dev_deploy.yml
- src/views/customer/components/ChronicInformation.vue
- src/views/customer/components/ChronicInformationChangeStatus.vue
- src/views/customer/components/FollowUpRecords.vue
> fix: 慢病管理页面ui

- src/views/customer/components/ChronicInformation.vue
- src/views/customer/components/ChronicInformationChangeStatus.vue
- src/views/customer/components/ChronicInformationFirstFollowUp.vue
> fix: 优化卡片展示、修改慢病状态

- src/api/followUpForm.js
- src/views/customer/components/AddFollowUpSheet.vue
- src/views/customer/components/ChronicInformation.vue
- src/views/customer/components/ChronicInformationChangeStatus.vue
- src/views/customer/components/ChronicInformationFirstFollowUp.vue
- src/views/customer/components/FollowUpRecords.vue
- src/views/customer/components/GradeModel.vue
- src/views/customer/components/SeeFollowUpSheet.vue
> fix: 随访单bug修复

- src/api/customer.js
- src/views/customer/components/ChronicInformationChangeStatus.vue
> fix: 优化修改慢病状态，新增慢病误判功能

- src/views/customer/components/AddFollowUpSheet.vue
- src/views/customer/components/ChronicInformation.vue
慢病管理页几个几个状态样式修改
增加创建时判断表单项名称不能为空提示
> fix: 慢病管理页样式修改

- src/api/chronic.js
- src/views/health/HealthChronic.vue
- src/views/health/HealthChronicEdit.vue
- src/views/health/HealthChronicSpeechModal.vue
- src/views/health/components/GradingStandard.vue
> feat: 新增话术功能，优化编辑慢病、分级、新建慢病功能

- src/views/customer/components/AddHealthCoaching.vue
- src/views/customer/components/ChronicInformation.vue
- src/views/customer/components/ChronicInformationChangeStatus.vue
- src/views/customer/components/ChronicInformationFirstFollowUp.vue
- src/views/customer/components/HealthCoachingRecords.vue
> feat: 增加健康指导，修改确诊与误判页面

- src/views/customer/components/DefineLevel.vue
- src/views/customer/components/FollowUpFormSend.vue
- src/views/customer/components/FollowUpRecords.vue
- src/views/customer/components/SeeFollowUpSheet.vue
> fix: 分级确认弹窗

- src/views/customer/components/FollowUpFormEdit.vue
> fix: 随访编辑单复选框bug

- src/views/customer/components/ChronicInformation.vue
前期是直接修改复查时间，下载改成了修改复查间隔，自动生成复查时间
> fix: 修改复查逻辑

- src/config/router.config.js
- src/locales/lang/zh-CN/menu.js
- src/views/customer/components/CustomerInfoForm.vue
- src/views/health/IndexPage.vue
https://www.leangoo.com/kanban/board/go/4501789/0e6d4ed69c114438
> fix: 修复指标管理一些bug

- src/views/health/HealthChronic.vue
- src/views/system/AccountList.vue
- src/views/system/PermissionList.vue
> fix: 症状管理和账户管理添加小功能

- src/views/customer/CustomerManager.vue
- src/views/customer/components/HealthReportAdd.vue
https://www.leangoo.com/kanban/board/go/4589908/0418e66be1c34328
https://www.leangoo.com/kanban/board/go/4589908/ccc6b0d72021a5a6
> feat: 升级添加小功能

- src/views/customer/components/HealthReportAdd.vue
- src/views/health/HealthChronic.vue
https://www.leangoo.com/kanban/board/go/4589908/e7b34bc5aec16a51
> feat: 新建慢病和新增健康报告中新增小功能

- src/views/customer/CustomerManager.vue
- src/views/customer/components/SeeUserMsg.vue
> fix: 优化用户个人信息展示

- src/api/chronic.js
- src/views/health/HealthChronic.vue
- src/views/health/HealthChronicEdit.vue
> fix: 完善慢病指标编辑

- src/views/health/HealthChronic.vue
- src/views/health/HealthChronicMedicine.vue
> feat: 新增慢病药物资料管理功能

- src/views/customer/components/HealthReportSee.vue
- src/views/health/IndexPage.vue
https://www.leangoo.com/kanban/board/go/4605175/fa34bd5135760545
> feat: 新增指标备注

- src/views/customer/components/FollowUpFormEdit.vue
- src/views/customer/components/SeeFollowUpSheet.vue
https://www.leangoo.com/kanban/board/go/4605175/8f51493f08c631a0
> feat: 查看随访单时新增指标项目

- src/views/customer/components/CustomerInfoForm.vue
- src/views/customer/components/EditUserMsg.vue
- src/views/customer/components/SeeUserMsg.vue
> fix: 增加单位和社区字段，优化用户编辑

- src/api/medicine.js
- src/config/router.config.js
- src/views/health/ChronicMedicineManage.vue
- src/views/health/HealthChronic.vue
- src/views/health/HealthChronicMedicine.vue
- src/views/health/components/ChronicMedicineAdd.vue
> feat: 新增慢药物管理、慢病管理下的药物功能

- src/views/customer/components/HealthReportAdd.vue
- src/views/customer/components/HealthReportSee.vue
- src/views/station/AppointmentRecord.vue
- src/views/station/StationManage.vue
- src/views/station/components/EditEquipment.vue
- src/views/station/components/StationEquipment.vue
新增小站设备（未接接口），查看健康报告在小结中显示图文报告的备注，修改报告标题背景色
> feat: 小站设备、健康报告

- src/views/customer/CustomerManager.vue
- src/views/health/components/ChronicMedicineAdd.vue
- src/views/system/AccountList.vue
1. 优化用户管理页面
2. 优化账户管理页面，新增状态查询功能
3. 优化药物管理--药物添加
> feat: 修改缺陷

- public/index.html
- src/views/disease/ChronicDisease.vue
- src/views/health/ChronicMedicineManage.vue
- src/views/health/components/ChronicMedicineAdd.vue
- src/views/station/AppointmentRecord.vue
- src/views/station/StationManage.vue
- src/views/system/AccountList.vue
- src/views/system/PermissionList.vue
1.添加页面刷新功能。2.优化系统加载页面。3.优化药物管理交互。4.优化药物管理新建/编辑框交互。5.优化账户管理
> feat: 1.添加页面刷新功能。2.优化系统加载页面。3.优化药物管理交互。4.优化药物管理新建/编辑框交互。5.优化账户管理

- src/views/customer/components/FollowUpRecords.vue
- src/views/customer/components/PrintFollowUp.vue
> feat: 新增随访单打印功能

- src/views/health/components/ChronicMedicineAdd.vue
> fix: 药物管理 - 新增漏服用法

- src/api/customer.js
- src/api/manage.js
- src/views/customer/CustomerManager.vue
- src/views/customer/components/HealthDataManagmentForm.vue
- src/views/system/AccountList.vue
- src/views/system/AssignDuty.vue
1.用户管理：新增查看负责家庭功能
2.账户管理：新增责任分配功能
3.用户管理：健康报告打印
> feat: 1.用户管理：新增查看负责家庭功能；2.账户管理：新增责任分配功能

- src/api/guidance.js
- src/utils/request.js
- src/views/customer/components/AddHealthCoaching.vue
- src/views/customer/components/HealthCoachingRecords.vue
- src/views/customer/components/HealthCoachingSend.vue
1.用户管理-慢病管理：优化健康指导发送(至小程序)，优化健康指导记录展示
> fix: 1.用户管理-慢病管理：优化健康指导发送(至小程序)，优化健康指导记录展示

- src/config/router.config.js
- src/locales/lang/zh-CN/menu.js
- src/views/afterSale/saleInstall.vue
- src/views/afterSale/saleInstallModal.vue
- src/views/afterSale/saleRepair.vue
- src/views/afterSaleData/salePartManage.vue
- src/views/afterSaleData/saleQuestionManage.vue
- src/views/system/AccountList.vue
> feat: 售后管理

- src/config/router.config.js
- src/views/afterSale/saleRepair.vue
- src/views/afterSale/saleRepairModal.vue
> fix: 优化售后管理界面

- src/views/afterSale/saleRepairModal.vue
- src/views/afterSaleData/saleQuestionManage.vue
> fix: 售后管理:优化配件选择

- src/views/afterSale/saleRepairAdd.vue
> fix: 售后管理:优化文件上传

- src/api/afterSale.js
- src/views/afterSaleData/saleQuestionEdit.vue
- src/views/afterSaleData/saleQuestionManage.vue
> fix: 售后管理：售后问题管理

- src/views/afterSale/saleRepairModal.vue
> fix: 售后管理：优化售后客户信息展示

- src/views/afterSale/saleRepair.vue
- src/views/afterSale/saleRepairModal.vue
> fix: 售后管理：时间排序

- src/views/afterSale/saleRepair.vue
- src/views/afterSale/saleRepairModal.vue
优化缺陷：
保修期内改折扣；
评估次数列；
数据时间排序；
上门配件不为空；
单独滑动；
已支付填单
> fix: 售后管理：优化缺陷：保修期内改折扣；评估次数列；数据时间排序；上门配件不为空；单独滑动；已支付填单

- src/views/afterSale/saleRepair.vue
- src/views/afterSale/saleRepairAdd.vue
- src/views/afterSale/saleRepairModal.vue
优化缺陷: 
技术人员选择；
新增品牌、型号、编号；
技术电话两位；
快递品牌; 
优化展示
> fix: 售后管理：优化缺陷: 技术人员选择；新增品牌、型号、编号；技术电话两位；快递品牌; 优化展示

- src/views/afterSale/saleRepair.vue
> fix: 售后管理：售后搜索

- src/views/afterSale/saleRepair.vue
- src/views/afterSale/saleRepairAdd.vue
- src/views/afterSale/saleRepairModal.vue
> fix: 售后管理：问题优化

- src/api/afterSale.js
- src/views/afterSale/saleRepair.vue
- src/views/afterSale/saleRepairAdd.vue
- src/views/afterSale/saleRepairModal.vue
> fix: 售后管理：删除月结工单

- src/api/afterSale.js
- src/views/afterSale/saleRepair.vue
- src/views/afterSale/saleRepairAdd.vue
- src/views/afterSale/saleRepairModal.vue
> fix: 售后管理：还原

- src/api/health.js
- src/views/account/settings/AvatarModal.vue
- src/views/account/settings/BasicSetting.vue
- src/views/afterSale/saleInstall.vue
- src/views/afterSale/saleInstallAdd.vue
- src/views/afterSale/saleInstallModal.vue
- src/views/afterSale/saleRepairAdd.vue
- src/views/afterSale/saleRepairModal.vue
- src/views/customer/components/HealthReportAdd.vue
售后管理：优化月结单显示、安装管理；
用户管理：新增慢病自动分析判断；
账户管理：新增编辑个人信息
> fix: 售后管理：优化月结单显示、安装管理；用户管理：新增慢病自动分析判断；账户管理：新增编辑个人信息

- src/api/login.js
- src/components/GlobalHeader/RightContent.vue
- src/views/account/settings/BasicSetting.vue
- src/views/account/settings/Security.vue
- src/views/system/AccountList.vue
账户管理：
优化账户名显示；
新增编辑账户信息；
新增账户密码和手机号的修改（未完成）
> fix: 账户管理：优化账户名显示；新增编辑账户信息；新增账户密码和手机号的修改（未完成）

- src/components/GlobalHeader/RightContent.vue
> fix: 账户管理：登陆后账户名未显示

- src/api/login.js
- src/api/station.js
- src/views/account/settings/Security.vue
- src/views/station/StationManage.vue
- src/views/station/components/EditEquipment.vue
- src/views/station/components/StationEquipment.vue
账户管理：
新增更改账户密码；新增更改账户手机号(未完)；
小站管理：
优化小站内容显示;
新增新建设备、编辑设备、删除设备功能
> fix: 账户管理：新增更改账户密码；新增更改账户手机号(未完)；小站管理：优化小站内容显示，新增新建设备、编辑设备、删除设备功能

- src/api/login.js
- src/components/GlobalHeader/RightContent.vue
- src/views/account/settings/Security.vue
- src/views/station/components/EditEquipment.vue
- src/views/station/components/StationEquipment.vue
> fix: 账户管理：完善更改账户手机号；小站管理：完善删除设备

- src/api/login.js
- src/config/router.config.js
- src/store/modules/user.js
- src/views/user/Login.vue
> fix: 完善手机号登录，待优化

- src/utils/request.js
- src/views/health/HealthChronic.vue
- src/views/user/Login.vue
> fix: 优化登录；增加接口请求时间

- src/views/user/Login.vue
> fix: 优化首次登陆

- src/views/afterSale/saleRepairModal.vue
售后管理：0元支付、配件编码和id存储、再评估时作废最近流程
> fix: 售后管理：0元支付、配件编码和id存储、再评估时作废最近流程

- src/views/afterSale/saleRepairModal.vue
> fix: 售后管理：0元评估不记录内勤

- src/views/afterSale/saleRepair.vue
- src/views/customer/CustomerManager.vue
- src/views/customer/components/SeeUserMsg.vue
用户管理：
优化创建者展示；
优化用户个人信息出生年月日展示；
优化搜索功能(未完善)；
售后管理：
提取新建工单
> fix: 用户管理：优化创建者展示；优化用户个人信息出生年月日展示；优化搜索功能(未完善)；售后管理：提取新建工单

- src/views/customer/components/AddHealthCoaching.vue
> fix: 用户管理：健康指导模板加载

- src/config/router.config.js
> fix: 售后管理：安装

- src/views/account/settings/BasicSetting.vue
- src/views/afterSale/saleRepairAdd.vue
- src/views/afterSale/saleRepairModal.vue
售后管理：新建工单标题、优化评估界面；
系统管理：个人信息编辑添加校验
> fix: 售后管理：新建工单标题、优化评估界面；系统管理：个人信息编辑添加校验

- src/views/afterSale/saleRepair.vue
- src/views/afterSale/saleRepairModal.vue
- src/views/afterSale/saleRepairModalAgainEstimate.vue
售后管理：
月结单问题；
在评估记录；
未解决记录；
寄件/上门信息拆分；
售后界面优化
> fix: 售后管理：月结单问题；在评估记录；为解决记录；寄件/上门信息拆分；售后界面优化

- src/views/afterSale/saleRepair.vue
- src/views/afterSale/saleRepairAdd.vue
- src/views/afterSale/saleRepairModal.vue
- src/views/customer/components/DefineLevel.vue
售后管理：
优化搜索，新增时间筛选
界面优化
解决是否月结单选项变大问题
> fix: 售后管理：优化搜索，新增时间筛选；界面优化；解决是否月结单选项变大问题

- src/views/afterSale/saleRepair.vue
> fix: 售后管理：售后工单筛选时间

- src/views/afterSale/saleRepair.vue
> fix: 售后管理：售后工单筛选时间排序

- src/views/product/productModel .vue
- src/views/product/productModelModal.vue
> fix: 售后管理：产品型号库

- src/views/afterSale/saleRepair.vue
- src/views/product/productModel .vue
- src/views/product/productModelModal.vue
> fix: 售后管理：产品型号库优化；维修管理优化

- src/views/afterSaleData/saleQuestionManage.vue
> fix: 售后管理：售后问题库优化

- src/views/afterSale/saleRepairAdd.vue
- src/views/afterSale/saleRepairModal.vue
售后管理：
维修管理-新建工单月结单可去选；
维修管理-技术人员替换；
> fix: 售后管理：维修管理-新建工单月结单可去选；维修管理-技术人员替换

- src/views/health/HealthChronic.vue
- src/views/health/HealthChronicEdit.vue
病症管理 - 新建慢病 - 指标添加异常;
病症管理 - 编辑慢病 - 添加指标做二次确认;
> fix: 病症管理 - 新建慢病 - 指标添加异常;病症管理 - 编辑慢病 - 添加指标做二次确认

- src/views/afterSale/saleRepair.vue
- src/views/afterSaleData/saleQuestionManage.vue
售后资料管理 - 问题管理 - 刷新
售后管理 - 维修管理 - 刷新
> fix: 售后资料管理 - 问题管理 - 刷新;售后管理 - 维修管理 - 刷新

- src/views/account/settings/Security.vue
- src/views/afterSale/saleRepairModal.vue
- src/views/customer/components/HealthDataManagmentForm.vue
- src/views/customer/components/HealthReportSee.vue
个人设置 - 更改密码：优化按钮；
售后管理 - 判断上门：上门默认为0bug；
健康信息 - 打印：用户诊断打印文件bug；
> fix: 个人设置 - 更改密码：优化按钮；售后管理 - 判断上门：上门默认为0bug；健康信息 - 打印：用户诊断打印文件bug；

- src/views/customer/components/HealthDataManagmentForm.vue
> fix: 清理console.log

- src/views/afterSale/saleRepair.vue
- src/views/afterSale/saleRepairModal.vue
售后管理：
1、列表过滤；
2、0元支付寄件上门；
3、待评估修改客户信息
> fix: 售后管理：1、列表过滤；2、0元支付寄件上门；3、待评估修改客户信息

- src/views/afterSale/saleRepairModal.vue
> fix: 售后管理：已寄件：保存寄件信息

- src/views/afterSale/saleRepairModal.vue
> fix: 售后管理：优化已寄件保存；新增待上门修改

- src/views/afterSale/saleRepair.vue
- src/views/afterSale/saleRepairModal.vue
返工
售后管理：
选择月结单---无反馈；
待上门按键位置；
> fix: 返工：售后管理：选择月结单---无反馈；待上门按键位置

- src/views/afterSale/saleRepairModal.vue
> fix: 售后管理：优化待上门修改上门信息

- src/views/afterSale/saleRepair.vue
> fix: 售后管理 - 维修管理：日期筛选框显示不完整

- src/views/afterSale/saleRepairModal.vue
> fix: 售后管理 - 维修管理：需寄件不上门异常

- src/views/afterSaleData/saleQuestionManage.vue
> fix: 售后管理 - 维修管理：按钮位置
